// Tabela de Etnias Indígenas Brasileiras — Portaria SAS/MS nº 508, de 28/09/2010, Anexo I.
// 264 etnias (códigos 0001–0264). Gerado a partir do PDF oficial — não editar à mão.
// O campo Etnia só é exigido quando Raça/Cor = Indígena (Art. 2º). Para os demais,
// fica VAZIO — a Portaria não define código para não-indígenas.
import type { ComboOption } from "@/lib/bpa-i-v2/racas";

export const ETNIAS: ComboOption[] = [
  { code: "0001", label: "ACONA", search: "acona wakonas naconas jakona acora nes" },
  { code: "0002", label: "AIKANA", search: "aikana aikana massaka tubarao" },
  { code: "0003", label: "AJURU", search: "ajuru" },
  { code: "0004", label: "AKUNSU", search: "akunsu akunt su" },
  { code: "0005", label: "A M A N AY E", search: "a m a n ay e" },
  { code: "0006", label: "A M O N D AWA", search: "a m o n d awa" },
  { code: "0007", label: "ANAMBE", search: "anambe" },
  { code: "0008", label: "APARAI", search: "aparai apalai" },
  { code: "0009", label: "APIAKA", search: "apiaka apiaca" },
  { code: "0010", label: "APINAYE", search: "apinaye apinaje apinaie apinage" },
  { code: "0011", label: "APURINA", search: "apurina aporina ipurina ipurina nan ipuri" },
  { code: "0012", label: "ARANA", search: "arana aracuai do vale do jequitinhonha" },
  { code: "0013", label: "ARAPASO", search: "arapaso arapaco" },
  { code: "0014", label: "ARARA DE RONDONIA", search: "arara de rondonia karo urucu uruku" },
  { code: "0015", label: "ARARA DO ACRE", search: "arara do acre shawanaua amawaka" },
  { code: "0016", label: "ARARA DO ARIPUANA", search: "arara do aripuana arara do beiradao ari puana" },
  { code: "0017", label: "ARARA DO PARA", search: "arara do para ukaragma ukaramma" },
  { code: "0018", label: "ARAWETE", search: "arawete arauete" },
  { code: "0019", label: "ARIKAPU", search: "arikapu aricapu arikapo masubi maxubi" },
  { code: "0020", label: "ARIKEM", search: "arikem ariquen ariqueme arikeme" },
  { code: "0021", label: "ARIKOSE", search: "arikose aricobe" },
  { code: "0022", label: "ARUA", search: "arua" },
  { code: "0023", label: "ARUAK", search: "aruak arawak" },
  { code: "0024", label: "ASHANINKA", search: "ashaninka kampa" },
  { code: "0025", label: "ASURINI DO TOCANTINS", search: "asurini do tocantins akuawa akwawa" },
  { code: "0026", label: "ASURINI DO XINGU", search: "asurini do xingu awaete" },
  { code: "0027", label: "ATIKUM", search: "atikum aticum" },
  { code: "0028", label: "AVA - C A N O E I R O", search: "ava c a n o e i r o" },
  { code: "0029", label: "AWETI", search: "aweti aueti aueto" },
  { code: "0030", label: "BAKAIRI", search: "bakairi kura bacairi" },
  { code: "0031", label: "BANAWA YAFI", search: "banawa yafi banawa banawa jafi" },
  { code: "0032", label: "BANIWA", search: "baniwa baniua baniva walimanai wakue nai" },
  { code: "0033", label: "BARA", search: "bara waipinomaka" },
  { code: "0034", label: "BARASANA", search: "barasana hanera" },
  { code: "0035", label: "BARE", search: "bare" },
  { code: "0036", label: "BORORO", search: "bororo boe" },
  { code: "0037", label: "BOTOCUDO", search: "botocudo geren" },
  { code: "0038", label: "CANOE", search: "canoe" },
  { code: "0039", label: "C A S S U PA", search: "c a s s u pa" },
  { code: "0040", label: "CHAMACOCO", search: "chamacoco" },
  { code: "0041", label: "CHIQUITANO", search: "chiquitano xiquitano" },
  { code: "0042", label: "CIKIYANA", search: "cikiyana sikiana" },
  { code: "0043", label: "CINTA LARGA", search: "cinta larga matetamae" },
  { code: "0044", label: "COLUMBIARA", search: "columbiara corumbiara" },
  { code: "0045", label: "DENI", search: "deni" },
  { code: "0046", label: "DESANA                  DESANO, DESSANO, WIRA,", search: "desana desano dessano wira" },
  { code: "0047", label: "DIAHUI", search: "diahui jahoi jahui diarroi" },
  { code: "0048", label: "ENAWENE-NAWE", search: "enawene nawe saluma" },
  { code: "0049", label: "FULNI-O", search: "fulni o" },
  { code: "0050", label: "GALIBI", search: "galibi galibi do oiapoque karinha" },
  { code: "0051", label: "GALIBI MARWORNO", search: "galibi marworno galibi do uaca arua" },
  { code: "0052", label: "GAVIAO DE RONDONIA", search: "gaviao de rondonia digut" },
  { code: "0053", label: "GAVIAO KRIKATEJE", search: "gaviao krikateje" },
  { code: "0054", label: "GAVIAO PARKATEJE", search: "gaviao parkateje parkateje" },
  { code: "0055", label: "GAVIAO PUKOBIE", search: "gaviao pukobie pukobie pykopje gaviao do maranhao" },
  { code: "0056", label: "GUAJA", search: "guaja awa ava" },
  { code: "0057", label: "GUAJAJARA", search: "guajajara tenetehara" },
  { code: "0058", label: "GUARANI KAIOWA", search: "guarani kaiowa pai tavytera" },
  { code: "0059", label: "GUARANI M'BYA", search: "guarani m bya" },
  { code: "0060", label: "GUARANI NANDEVA", search: "guarani nandeva avakatuete chiripa" },
  { code: "0061", label: "G U ATO", search: "g u ato" },
  { code: "0062", label: "HIMARIMA", search: "himarima himerima" },
  { code: "0063", label: "INGARIKO", search: "ingariko ingarico akawaio kapon" },
  { code: "0064", label: "IRANXE", search: "iranxe irantxe" },
  { code: "0065", label: "ISSE", search: "isse" },
  { code: "0066", label: "JABOTI", search: "jaboti jabuti kipiu yabyti" },
  { code: "0067", label: "JAMAMADI", search: "jamamadi yamamadi djeoromitxi" },
  { code: "0068", label: "J A R AWA R A", search: "j a r awa r a" },
  { code: "0069", label: "JIRIPANCO", search: "jiripanco jeripanco geripanco" },
  { code: "0070", label: "JUMA", search: "juma yuma" },
  { code: "0071", label: "JURUNA", search: "juruna" },
  { code: "0072", label: "JURUTI", search: "juruti yuriti" },
  { code: "0073", label: "KAAPOR", search: "kaapor urubu kaapor ka apor kaaporte" },
  { code: "0074", label: "KADIWEU", search: "kadiweu caduveo cadiueu" },
  { code: "0075", label: "KAIABI", search: "kaiabi caiabi kayabi" },
  { code: "0076", label: "KAIMBE", search: "kaimbe caimbe" },
  { code: "0077", label: "KAINGANG", search: "kaingang caingangue" },
  { code: "0078", label: "KAIXANA", search: "kaixana caixana" },
  { code: "0079", label: "KALABASSA", search: "kalabassa calabassa calabacas" },
  { code: "0080", label: "KALANCO", search: "kalanco" },
  { code: "0081", label: "KALAPALO", search: "kalapalo calapalo" },
  { code: "0082", label: "KAMAYURA", search: "kamayura camaiura kamaiura" },
  { code: "0083", label: "KAMBA", search: "kamba camba" },
  { code: "0084", label: "KAMBEBA", search: "kambeba cambeba omagua" },
  { code: "0085", label: "KAMBIWA", search: "kambiwa cambiua" },
  { code: "0086", label: "KAMBIWA PIPIPA", search: "kambiwa pipipa pipipa" },
  { code: "0087", label: "KAMPE", search: "kampe" },
  { code: "0088", label: "KANAMANTI", search: "kanamanti kanamati canamanti" },
  { code: "0089", label: "KANAMARI", search: "kanamari canamari kanamary tukuna" },
  { code: "0090", label: "KANELA APANIEKRA", search: "kanela apaniekra canela" },
  { code: "0091", label: "KANELA RANKOKAMEKRA", search: "kanela rankokamekra canela" },
  { code: "0092", label: "KANINDE", search: "kaninde" },
  { code: "0093", label: "KANOE", search: "kanoe canoe" },
  { code: "0094", label: "KANTARURE", search: "kantarure cantarure" },
  { code: "0095", label: "KAPINAWA", search: "kapinawa capinaua" },
  { code: "0096", label: "KARAJA", search: "karaja caraja" },
  { code: "0097", label: "KARAJA/JAVAE", search: "karaja javae javae" },
  { code: "0098", label: "KARAJA/XAMBIOA", search: "karaja xambioa karaja do norte" },
  { code: "0099", label: "KARAPANA", search: "karapana carapana muteamasa ukopino pona" },
  { code: "0100", label: "KARAPOTO", search: "karapoto carapoto" },
  { code: "0101", label: "KARIPUNA", search: "karipuna caripuna" },
  { code: "0102", label: "KARIPUNA DO AMAPA", search: "karipuna do amapa caripuna" },
  { code: "0103", label: "KARIRI", search: "kariri cariri" },
  { code: "0104", label: "KARIRI-XOCO", search: "kariri xoco cariri choco" },
  { code: "0105", label: "KARITIANA", search: "karitiana caritiana" },
  { code: "0106", label: "KATAWIXI TA U I C H", search: "katawixi ta u i c h katauixi katawin katawisi ca" },
  { code: "0107", label: "KATUENA", search: "katuena catuena katwena" },
  { code: "0108", label: "KATUKINA", search: "katukina peda djapa" },
  { code: "0109", label: "KATUKINA DO ACRE", search: "katukina do acre" },
  { code: "0110", label: "KAXARARI", search: "kaxarari caxarari" },
  { code: "0111", label: "KAXINAWA", search: "kaxinawa huni kuin cashinaua caxinaua" },
  { code: "0112", label: "KAXIXO", search: "kaxixo" },
  { code: "0113", label: "KAXUYANA", search: "kaxuyana caxuiana" },
  { code: "0114", label: "KAYAPO", search: "kayapo caiapo" },
  { code: "0115", label: "KAYAPO KARARAO", search: "kayapo kararao kararao" },
  { code: "0116", label: "KAYAPO TXUKAHAMAE", search: "kayapo txukahamae txukahamae" },
  { code: "0117", label: "KAYAPO XICRIM", search: "kayapo xicrim xikrin" },
  { code: "0118", label: "KAYUISANA", search: "kayuisana caixana cauixana kaixana" },
  { code: "0119", label: "KINIKINAWA", search: "kinikinawa guan koinukoen kinikinao" },
  { code: "0120", label: "KIRIRI", search: "kiriri" },
  { code: "0121", label: "KOCAMA", search: "kocama cocama kokama" },
  { code: "0122", label: "KOKUIREGATEJE", search: "kokuiregateje" },
  { code: "0123", label: "KORUBO", search: "korubo" },
  { code: "0124", label: "KRAHO", search: "kraho crao krao" },
  { code: "0125", label: "KREJE", search: "kreje krenye" },
  { code: "0126", label: "KRENAK", search: "krenak borun crenaque" },
  { code: "0127", label: "KRIKATI", search: "krikati krinkati" },
  { code: "0128", label: "KUBEO", search: "kubeo cubeo cobewa kubewa pamiwa cu beu" },
  { code: "0129", label: "KUIKURO", search: "kuikuro kuikuru cuicuro" },
  { code: "0130", label: "KUJUBIM", search: "kujubim kuyubi cujubim" },
  { code: "0131", label: "KULINA PANO", search: "kulina pano culina" },
  { code: "0132", label: "KULINA/MADIHA", search: "kulina madiha culina madija madiha" },
  { code: "0133", label: "KURIPAKO", search: "kuripako curipaco curripaco coripaco wa k u e n a i" },
  { code: "0134", label: "KURUAIA", search: "kuruaia curuaia" },
  { code: "0135", label: "KWAZA", search: "kwaza coaia koaia" },
  { code: "0136", label: "MACHINERI", search: "machineri manchineri manxineri" },
  { code: "0137", label: "MACURAP", search: "macurap makurap" },
  { code: "0138", label: "MAKU DOW", search: "maku dow dow" },
  { code: "0139", label: "MAKU HUPDA", search: "maku hupda hupda" },
  { code: "0140", label: "MAKU NADEB", search: "maku nadeb nadeb" },
  { code: "0141", label: "MAKU YUHUPDE", search: "maku yuhupde yuhupde" },
  { code: "0142", label: "MAKUNA", search: "makuna macuna yeba masa" },
  { code: "0143", label: "MAKUXI", search: "makuxi macuxi machusi pemon" },
  { code: "0144", label: "MARIMAM", search: "marimam marima" },
  { code: "0145", label: "MARUBO", search: "marubo" },
  { code: "0146", label: "M AT I P U", search: "m at i p u" },
  { code: "0147", label: "M AT I S", search: "m at i s" },
  { code: "0148", label: "MATSE", search: "matse mayoruna" },
  { code: "0149", label: "MAXAKALI", search: "maxakali maxacali" },
  { code: "0150", label: "MAYA", search: "maya maya" },
  { code: "0151", label: "M AY TA P U", search: "m ay ta p u" },
  { code: "0152", label: "MEHINAKO", search: "mehinako meinaku meinacu" },
  { code: "0153", label: "MEKEN", search: "meken mequem mekhem michens" },
  { code: "0154", label: "MENKY", search: "menky myky munku menki mynky" },
  { code: "0155", label: "MIRANHA", search: "miranha miranha mirana" },
  { code: "0156", label: "MIRITI TAPUIA", search: "miriti tapuia miriti tapuya buia tapuya" },
  { code: "0157", label: "MUNDURUKU", search: "munduruku mundurucu" },
  { code: "0158", label: "MURA", search: "mura" },
  { code: "0159", label: "NAHUKWA", search: "nahukwa nafuqua" },
  { code: "0160", label: "NAMBIKWARA DO CAMPO", search: "nambikwara do campo halotesu kithaulu wakalitesu sawentes" },
  { code: "0161", label: "NAMBIKWARA DO NORTE", search: "nambikwara do norte negarote mamain de latunde sabane e" },
  { code: "0162", label: "NAMBIKWARA DO SUL", search: "nambikwara do sul wasusu hahaintesu alantesu waikisu alaketesu" },
  { code: "0163", label: "NARAVUTE", search: "naravute naruvoto" },
  { code: "0164", label: "NAWA", search: "nawa naua" },
  { code: "0165", label: "NUKINI", search: "nukini nuquini nukuini" },
  { code: "0166", label: "OFAIE", search: "ofaie ofaye xavante" },
  { code: "0167", label: "ORO WIN", search: "oro win" },
  { code: "0168", label: "PAIAKU", search: "paiaku jenipapo kaninde" },
  { code: "0169", label: "PAKAA NOVA", search: "pakaa nova wari pacaas novos" },
  { code: "0170", label: "PALIKUR", search: "palikur aukwayene aukuyene paliku ene" },
  { code: "0171", label: "PANARA", search: "panara krenhakarore krenakore krena karore" },
  { code: "0172", label: "PANKARARE", search: "pankarare pancarare" },
  { code: "0173", label: "PANKARARU", search: "pankararu pancararu" },
  { code: "0174", label: "PANKARARU KALANKO", search: "pankararu kalanko kalanko" },
  { code: "0175", label: "PANKARARU KARUAZU", search: "pankararu karuazu karuazu" },
  { code: "0176", label: "PANKARU", search: "pankaru pancaru" },
  { code: "0177", label: "PARAKANA", search: "parakana paracana apiterewa awaete" },
  { code: "0178", label: "PARECI", search: "pareci paresi haliti" },
  { code: "0179", label: "PA R I N T I N T I N", search: "pa r i n t i n t i n" },
  { code: "0180", label: "PATAMONA", search: "patamona kapon" },
  { code: "0181", label: "PATA X O", search: "pata x o" },
  { code: "0182", label: "PATAXO HA-HA-HAE", search: "pataxo ha ha hae" },
  { code: "0183", label: "PAUMARI", search: "paumari palmari" },
  { code: "0184", label: "PA U M E L E N H O", search: "pa u m e l e n h o" },
  { code: "0185", label: "PIRAHA", search: "piraha mura piraha" },
  { code: "0186", label: "PIRATUAPUIA", search: "piratuapuia piratapuya tapuya piratapuyo pira" },
  { code: "0187", label: "P I TA G U A R I", search: "p i ta g u a r i" },
  { code: "0188", label: "POTIGUARA", search: "potiguara" },
  { code: "0189", label: "POYANAWA", search: "poyanawa poianaua" },
  { code: "0190", label: "RIKBAKTSA", search: "rikbaktsa canoeiros erigpaktsa" },
  { code: "0191", label: "SAKURABIAT", search: "sakurabiat mekens sakirabiap biar sakira" },
  { code: "0192", label: "SATERE-MAWE", search: "satere mawe satere maue" },
  { code: "0193", label: "SHANENAWA", search: "shanenawa katukina" },
  { code: "0194", label: "SIRIANO", search: "siriano siria masa" },
  { code: "0195", label: "SURIANA", search: "suriana" },
  { code: "0196", label: "SURUI DE RONDONIA", search: "surui de rondonia paiter" },
  { code: "0197", label: "SURUI DO PARA", search: "surui do para aikewara" },
  { code: "0198", label: "SUYA", search: "suya suia kisedje" },
  { code: "0199", label: "TAPAYUNA", search: "tapayuna beico de pau" },
  { code: "0200", label: "TA P E B A", search: "ta p e b a" },
  { code: "0201", label: "TAPIRAPE", search: "tapirape tapi irape" },
  { code: "0202", label: "TAPUIA", search: "tapuia tapuia xavante tapuio" },
  { code: "0203", label: "TARIANO", search: "tariano tariana taliaseri" },
  { code: "0204", label: "TAUREPANG", search: "taurepang taulipang pemon arekuna pageyn" },
  { code: "0205", label: "TEMBE", search: "tembe" },
  { code: "0206", label: "TENHARIM", search: "tenharim" },
  { code: "0207", label: "TERENA", search: "terena" },
  { code: "0208", label: "TICUNA", search: "ticuna tikuna tukuna maguta" },
  { code: "0209", label: "TINGUI BOTO", search: "tingui boto" },
  { code: "0210", label: "TIRIYO EWARHUYANA YAWI,", search: "tiriyo ewarhuyana yawi tiriyo trio tarona" },
  { code: "0211", label: "TIRIYO KAH'YANA", search: "tiriyo kah yana tiriyo trio tarona yawi p i a n o k o to" },
  { code: "0212", label: "TIRIYO TSIKUYANA", search: "tiriyo tsikuyana tiriyo trio tarona yawi p i a n o k o to" },
  { code: "0213", label: "TO R A", search: "to r a" },
  { code: "0214", label: "TREMEMBE", search: "tremembe" },
  { code: "0215", label: "TRUKA", search: "truka" },
  { code: "0216", label: "TRUMAI", search: "trumai" },
  { code: "0217", label: "TSOHOM DJAPA", search: "tsohom djapa tsunhum djapa" },
  { code: "0218", label: "TUKANO", search: "tukano tucano ye pa masa dasea" },
  { code: "0219", label: "TUMBALALA", search: "tumbalala" },
  { code: "0220", label: "T U N AYA N A", search: "t u n aya n a" },
  { code: "0221", label: "T U PA R I", search: "t u pa r i" },
  { code: "0222", label: "TUPINAMBA", search: "tupinamba" },
  { code: "0223", label: "TUPINIQUIM", search: "tupiniquim" },
  { code: "0224", label: "T U R I WA R A", search: "t u r i wa r a" },
  { code: "0225", label: "TUXA", search: "tuxa" },
  { code: "0226", label: "TUYUKA", search: "tuyuka tuiuca dokapuara utapinomaka phona" },
  { code: "0227", label: "TXIKAO", search: "txikao txicao ikpeng" },
  { code: "0228", label: "UMUTINA", search: "umutina omotina barbados" },
  { code: "0229", label: "URU-EU-WAU-WAU", search: "uru eu wau wau urueu uau uau u r u pa urupain" },
  { code: "0230", label: "WAI WAI HIXKARYANA", search: "wai wai hixkaryana hixkaryana" },
  { code: "0231", label: "WAI WAI KARAFAWYANA", search: "wai wai karafawyana karafawyana kara paw ya n a" },
  { code: "0232", label: "WAI WAI XEREU", search: "wai wai xereu xereu" },
  { code: "0233", label: "WAI WAI KATUENA", search: "wai wai katuena katuena" },
  { code: "0234", label: "WAI WAI MAWAYANA", search: "wai wai mawayana mawayana" },
  { code: "0235", label: "WAIAPI", search: "waiapi wayampi oyampi wayapy" },
  { code: "0236", label: "WAIMIRI ATROARI", search: "waimiri atroari kina" },
  { code: "0237", label: "WANANO", search: "wanano uanano wanana" },
  { code: "0238", label: "WAPIXANA", search: "wapixana uapixana vapidiana wapisiana wa p i s h a n a" },
  { code: "0239", label: "WAREKENA", search: "warekena uarequena werekena" },
  { code: "0240", label: "WA S S U", search: "wa s s u" },
  { code: "0241", label: "WAURA", search: "waura uaura wauja" },
  { code: "0242", label: "WAYANA", search: "wayana waiana uaiana" },
  { code: "0243", label: "WITOTO", search: "witoto uitoto huitoto" },
  { code: "0244", label: "XAKRIABA", search: "xakriaba xacriaba" },
  { code: "0245", label: "XAVANTE", search: "xavante a uwe akwe awen akwen" },
  { code: "0246", label: "XERENTE", search: "xerente akwe awen akwen" },
  { code: "0247", label: "X E TA", search: "x e ta" },
  { code: "0248", label: "XIPAIA", search: "xipaia shipaya xipaya" },
  { code: "0249", label: "XOKLENG", search: "xokleng shokleng xocleng" },
  { code: "0250", label: "XOKO", search: "xoko xoco choco" },
  { code: "0251", label: "XUKURU", search: "xukuru xucuru" },
  { code: "0252", label: "XUKURU KARIRI", search: "xukuru kariri xucuru kariri" },
  { code: "0253", label: "YA I P I YA N A", search: "ya i p i ya n a" },
  { code: "0254", label: "YAMINAWA", search: "yaminawa jaminawa iaminawa" },
  { code: "0255", label: "YANOMAMI NINAM", search: "yanomami ninam ianomami ianoama xiria na" },
  { code: "0256", label: "YANOMAMI SANUMA", search: "yanomami sanuma ianomami ianoama xi riana" },
  { code: "0257", label: "YANOMAMI YANOMAM", search: "yanomami yanomam ianomami ianoama xi riana" },
  { code: "0258", label: "YAWALAPITI", search: "yawalapiti iaualapiti" },
  { code: "0259", label: "YAWANAWA", search: "yawanawa iauanaua" },
  { code: "0260", label: "YEKUANA", search: "yekuana maiongon m ay o n g o n ye kuana yekwana" },
  { code: "0261", label: "YUDJA", search: "yudja juruna yuruna" },
  { code: "0262", label: "ZO'E", search: "zo e poturu" },
  { code: "0263", label: "ZORO", search: "zoro pageyn" },
  { code: "0264", label: "ZURUAHA", search: "zuruaha sorowaha suruwaha" },
];
