// Tabela oficial de Tipo de Logradouro (DNE/Correios), usada pelo CADSUS (campo
// "Tipo de Logradouro" do BPA-I, código numérico de 3 dígitos — CADSUS RN026).
// 181 tipos. Gerado da tabela de domínio oficial — não editar à mão.
import type { ComboOption } from "@/lib/bpa-i-v2/racas";

export const TIPOS_LOGRADOURO: ComboOption[] = [
  { code: "001", label: "Acesso", search: "acesso" },
  { code: "002", label: "Adro", search: "adro" },
  { code: "004", label: "Alameda", search: "alameda" },
  { code: "005", label: "Alto", search: "alto" },
  { code: "007", label: "Atalho", search: "atalho" },
  { code: "008", label: "Avenida", search: "avenida" },
  { code: "009", label: "Balneario", search: "balneario" },
  { code: "010", label: "Belvedere", search: "belvedere" },
  { code: "011", label: "Beco", search: "beco" },
  { code: "012", label: "Bloco", search: "bloco" },
  { code: "013", label: "Bosque", search: "bosque" },
  { code: "014", label: "Boulevard", search: "boulevard" },
  { code: "015", label: "Baixa", search: "baixa" },
  { code: "016", label: "Cais", search: "cais" },
  { code: "017", label: "Caminho", search: "caminho" },
  { code: "019", label: "Chapadão", search: "chapadao" },
  { code: "020", label: "Conjunto", search: "conjunto" },
  { code: "021", label: "Colônia", search: "colonia" },
  { code: "022", label: "Corredor", search: "corredor" },
  { code: "023", label: "Campo", search: "campo" },
  { code: "024", label: "Córrego", search: "corrego" },
  { code: "027", label: "Desvio", search: "desvio" },
  { code: "028", label: "Distrito", search: "distrito" },
  { code: "030", label: "Escada", search: "escada" },
  { code: "031", label: "Estrada", search: "estrada" },
  { code: "032", label: "Estação", search: "estacao" },
  { code: "033", label: "Estádio", search: "estadio" },
  { code: "036", label: "Favela", search: "favela" },
  { code: "037", label: "Fazenda", search: "fazenda" },
  { code: "038", label: "Ferrovia", search: "ferrovia" },
  { code: "039", label: "Fonte", search: "fonte" },
  { code: "040", label: "Feira", search: "feira" },
  { code: "043", label: "Forte", search: "forte" },
  { code: "045", label: "Galeria", search: "galeria" },
  { code: "046", label: "Granja", search: "granja" },
  { code: "050", label: "Ilha", search: "ilha" },
  { code: "052", label: "Jardim", search: "jardim" },
  { code: "053", label: "Ladeira", search: "ladeira" },
  { code: "054", label: "Largo", search: "largo" },
  { code: "055", label: "Lagoa", search: "lagoa" },
  { code: "056", label: "Loteamento", search: "loteamento" },
  { code: "059", label: "Morro", search: "morro" },
  { code: "060", label: "Monte", search: "monte" },
  { code: "062", label: "Paralela", search: "paralela" },
  { code: "063", label: "Passeio", search: "passeio" },
  { code: "064", label: "Pátio", search: "patio" },
  { code: "065", label: "Praça", search: "praca" },
  { code: "067", label: "Parada", search: "parada" },
  { code: "070", label: "Praia", search: "praia" },
  { code: "071", label: "Prolongamento", search: "prolongamento" },
  { code: "072", label: "Parque", search: "parque" },
  { code: "073", label: "Passarela", search: "passarela" },
  { code: "074", label: "Passagem", search: "passagem" },
  { code: "076", label: "Ponte", search: "ponte" },
  { code: "077", label: "Quadra", search: "quadra" },
  { code: "079", label: "Quinta", search: "quinta" },
  { code: "081", label: "Rua", search: "rua" },
  { code: "082", label: "Ramal", search: "ramal" },
  { code: "087", label: "Recanto", search: "recanto" },
  { code: "088", label: "Retiro", search: "retiro" },
  { code: "089", label: "Reta", search: "reta" },
  { code: "090", label: "Rodovia", search: "rodovia" },
  { code: "091", label: "Retorno", search: "retorno" },
  { code: "092", label: "Sítio", search: "sitio" },
  { code: "094", label: "Servidão", search: "servidao" },
  { code: "095", label: "Setor", search: "setor" },
  { code: "096", label: "Subida", search: "subida" },
  { code: "097", label: "Trincheira", search: "trincheira" },
  { code: "098", label: "Terminal", search: "terminal" },
  { code: "099", label: "Trevo", search: "trevo" },
  { code: "100", label: "Travessa", search: "travessa" },
  { code: "101", label: "Via", search: "via" },
  { code: "103", label: "Viaduto", search: "viaduto" },
  { code: "104", label: "Vila", search: "vila" },
  { code: "105", label: "Viela", search: "viela" },
  { code: "106", label: "Vale", search: "vale" },
  { code: "108", label: "Zigue-zague", search: "zigue zague" },
  { code: "452", label: "Trecho", search: "trecho" },
  { code: "453", label: "Vereda", search: "vereda" },
  { code: "465", label: "Artéria", search: "arteria" },
  { code: "468", label: "Elevada", search: "elevada" },
  { code: "469", label: "Porto", search: "porto" },
  { code: "470", label: "Balão", search: "balao" },
  { code: "471", label: "Paradouro", search: "paradouro" },
  { code: "472", label: "Área", search: "area" },
  { code: "473", label: "Jardinete", search: "jardinete" },
  { code: "474", label: "Esplanada", search: "esplanada" },
  { code: "475", label: "Quintas", search: "quintas" },
  { code: "476", label: "Rotula", search: "rotula" },
  { code: "477", label: "Marina", search: "marina" },
  { code: "478", label: "Descida", search: "descida" },
  { code: "479", label: "Circular", search: "circular" },
  { code: "480", label: "Unidade", search: "unidade" },
  { code: "481", label: "Chácara", search: "chacara" },
  { code: "482", label: "Rampa", search: "rampa" },
  { code: "483", label: "Ponta", search: "ponta" },
  { code: "484", label: "Via de pedestre", search: "via de pedestre" },
  { code: "485", label: "Condomínio", search: "condominio" },
  { code: "486", label: "Habitacional", search: "habitacional" },
  { code: "487", label: "Residencial", search: "residencial" },
  { code: "495", label: "Canal", search: "canal" },
  { code: "496", label: "Buraco", search: "buraco" },
  { code: "497", label: "Módulo", search: "modulo" },
  { code: "498", label: "Estância", search: "estancia" },
  { code: "499", label: "Lago", search: "lago" },
  { code: "500", label: "Núcleo", search: "nucleo" },
  { code: "501", label: "Aeroporto", search: "aeroporto" },
  { code: "502", label: "Passagem Subterrânea", search: "passagem subterranea" },
  { code: "503", label: "Complexo Viário", search: "complexo viario" },
  { code: "504", label: "Praça de Esportes", search: "praca de esportes" },
  { code: "505", label: "Via Elevada", search: "via elevada" },
  { code: "506", label: "Rotatória", search: "rotatoria" },
  { code: "507", label: "1ª Travessa", search: "1 travessa" },
  { code: "508", label: "2ª Travessa", search: "2 travessa" },
  { code: "509", label: "3ª Travessa", search: "3 travessa" },
  { code: "510", label: "4ª Travessa", search: "4 travessa" },
  { code: "511", label: "5ª Travessa", search: "5 travessa" },
  { code: "512", label: "6ª Travessa", search: "6 travessa" },
  { code: "513", label: "7ª Travessa", search: "7 travessa" },
  { code: "514", label: "8ª Travessa", search: "8 travessa" },
  { code: "515", label: "9ª Travessa", search: "9 travessa" },
  { code: "516", label: "10ª Travessa", search: "10 travessa" },
  { code: "517", label: "11ª Travessa", search: "11 travessa" },
  { code: "518", label: "12ª Travessa", search: "12 travessa" },
  { code: "519", label: "13ª Travessa", search: "13 travessa" },
  { code: "520", label: "14ª Travessa", search: "14 travessa" },
  { code: "521", label: "15ª Travessa", search: "15 travessa" },
  { code: "522", label: "16ª Travessa", search: "16 travessa" },
  { code: "523", label: "1º Alto", search: "1 alto" },
  { code: "524", label: "2º Alto", search: "2 alto" },
  { code: "525", label: "3º Alto", search: "3 alto" },
  { code: "526", label: "4º Alto", search: "4 alto" },
  { code: "527", label: "5º Alto", search: "5 alto" },
  { code: "528", label: "1º Beco", search: "1 beco" },
  { code: "529", label: "2º Beco", search: "2 beco" },
  { code: "530", label: "3º Beco", search: "3 beco" },
  { code: "531", label: "4º Beco", search: "4 beco" },
  { code: "532", label: "5º Beco", search: "5 beco" },
  { code: "533", label: "1ª Paralela", search: "1 paralela" },
  { code: "534", label: "2ª Paralela", search: "2 paralela" },
  { code: "535", label: "3ª Paralela", search: "3 paralela" },
  { code: "536", label: "4ª Paralela", search: "4 paralela" },
  { code: "537", label: "5ª Paralela", search: "5 paralela" },
  { code: "538", label: "1ª Subida", search: "1 subida" },
  { code: "539", label: "2ª Subida", search: "2 subida" },
  { code: "540", label: "3ª Subida", search: "3 subida" },
  { code: "541", label: "4ª Subida", search: "4 subida" },
  { code: "542", label: "5ª Subida", search: "5 subida" },
  { code: "543", label: "6ª Subida", search: "6 subida" },
  { code: "544", label: "1ª Vila", search: "1 vila" },
  { code: "545", label: "2ª Vila", search: "2 vila" },
  { code: "546", label: "3ª Vila", search: "3 vila" },
  { code: "547", label: "4ª Vila", search: "4 vila" },
  { code: "548", label: "5ª Vila", search: "5 vila" },
  { code: "549", label: "1º Parque", search: "1 parque" },
  { code: "550", label: "2º Parque", search: "2 parque" },
  { code: "551", label: "3º Parque", search: "3 parque" },
  { code: "552", label: "1ª Rua", search: "1 rua" },
  { code: "553", label: "2ª Rua", search: "2 rua" },
  { code: "554", label: "3ª Rua", search: "3 rua" },
  { code: "555", label: "4ª Rua", search: "4 rua" },
  { code: "556", label: "5ª Rua", search: "5 rua" },
  { code: "557", label: "6ª Rua", search: "6 rua" },
  { code: "558", label: "7ª Rua", search: "7 rua" },
  { code: "559", label: "8ª Rua", search: "8 rua" },
  { code: "560", label: "9ª Rua", search: "9 rua" },
  { code: "561", label: "10ª Rua", search: "10 rua" },
  { code: "562", label: "11ª Rua", search: "11 rua" },
  { code: "563", label: "12ª Rua", search: "12 rua" },
  { code: "564", label: "Estacionamento", search: "estacionamento" },
  { code: "565", label: "Vala", search: "vala" },
  { code: "566", label: "Rua de Pedestre", search: "rua de pedestre" },
  { code: "567", label: "Túnel", search: "tunel" },
  { code: "568", label: "Variante", search: "variante" },
  { code: "569", label: "Rodo Anel", search: "rodo anel" },
  { code: "570", label: "Travessa Particular", search: "travessa particular" },
  { code: "571", label: "Calçada", search: "calcada" },
  { code: "572", label: "Via de Acesso", search: "via de acesso" },
  { code: "573", label: "Entrada Particular", search: "entrada particular" },
  { code: "645", label: "Acampamento", search: "acampamento" },
  { code: "646", label: "Via Expressa", search: "via expressa" },
];
