/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as BpaIV2RouteImport } from './routes/bpa-i-v2'
import { Route as BpaIRouteImport } from './routes/bpa-i'
import { Route as BpaCV2RouteImport } from './routes/bpa-c-v2'
import { Route as BpaCRouteImport } from './routes/bpa-c'
import { Route as IndexRouteImport } from './routes/index'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const BpaIV2Route = BpaIV2RouteImport.update({
  id: '/bpa-i-v2',
  path: '/bpa-i-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const BpaIRoute = BpaIRouteImport.update({
  id: '/bpa-i',
  path: '/bpa-i',
  getParentRoute: () => rootRouteImport,
} as any)
const BpaCV2Route = BpaCV2RouteImport.update({
  id: '/bpa-c-v2',
  path: '/bpa-c-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const BpaCRoute = BpaCRouteImport.update({
  id: '/bpa-c',
  path: '/bpa-c',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bpa-c': typeof BpaCRoute
  '/bpa-c-v2': typeof BpaCV2Route
  '/bpa-i': typeof BpaIRoute
  '/bpa-i-v2': typeof BpaIV2Route
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bpa-c': typeof BpaCRoute
  '/bpa-c-v2': typeof BpaCV2Route
  '/bpa-i': typeof BpaIRoute
  '/bpa-i-v2': typeof BpaIV2Route
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bpa-c': typeof BpaCRoute
  '/bpa-c-v2': typeof BpaCV2Route
  '/bpa-i': typeof BpaIRoute
  '/bpa-i-v2': typeof BpaIV2Route
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bpa-c' | '/bpa-c-v2' | '/bpa-i' | '/bpa-i-v2' | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bpa-c' | '/bpa-c-v2' | '/bpa-i' | '/bpa-i-v2' | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/bpa-c'
    | '/bpa-c-v2'
    | '/bpa-i'
    | '/bpa-i-v2'
    | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpaCRoute: typeof BpaCRoute
  BpaCV2Route: typeof BpaCV2Route
  BpaIRoute: typeof BpaIRoute
  BpaIV2Route: typeof BpaIV2Route
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpa-i-v2': {
      id: '/bpa-i-v2'
      path: '/bpa-i-v2'
      fullPath: '/bpa-i-v2'
      preLoaderRoute: typeof BpaIV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpa-i': {
      id: '/bpa-i'
      path: '/bpa-i'
      fullPath: '/bpa-i'
      preLoaderRoute: typeof BpaIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpa-c-v2': {
      id: '/bpa-c-v2'
      path: '/bpa-c-v2'
      fullPath: '/bpa-c-v2'
      preLoaderRoute: typeof BpaCV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bpa-c': {
      id: '/bpa-c'
      path: '/bpa-c'
      fullPath: '/bpa-c'
      preLoaderRoute: typeof BpaCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpaCRoute: BpaCRoute,
  BpaCV2Route: BpaCV2Route,
  BpaIRoute: BpaIRoute,
  BpaIV2Route: BpaIV2Route,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
