/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BpaCRouteImport } from './routes/bpa-c'
import { Route as IndexRouteImport } from './routes/index'

const BpaCRoute = BpaCRouteImport.update({
  id: '/bpa-c',
  path: '/bpa-c',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bpa-c': typeof BpaCRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bpa-c': typeof BpaCRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bpa-c': typeof BpaCRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bpa-c'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bpa-c'
  id: '__root__' | '/' | '/bpa-c'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BpaCRoute: typeof BpaCRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bpa-c': {
      id: '/bpa-c'
      path: '/bpa-c'
      fullPath: '/bpa-c'
      preLoaderRoute: typeof BpaCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BpaCRoute: BpaCRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
